# Generated by Django 5.0 on 2023-12-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductorvehiculo',
            name='modelovehiculo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='repuestos',
            name='repuestorequerido',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
