# Generated by Django 5.0 on 2024-01-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderApp', '0002_alter_conductorvehiculo_modelovehiculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductorvehiculo',
            name='contraseña',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
