# Generated by Django 5.0 on 2024-01-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderApp', '0003_conductorvehiculo_contraseña'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
