# Generated by Django 5.0 on 2024-01-22 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoderApp', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
