# Generated by Django 5.0 on 2024-01-25 20:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderApp', '0009_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConductorVehiculo',
        ),
        migrations.AddField(
            model_name='avatar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
